### ISSUE TITLE
Chameleon App

### ISSUE THREAD

**Issue by r1ddl3rz** [RfidResearchGroup/ChameleonMini#11]
@willok @RfidResearchGroup 
Will the source code of the chameleon app be published?
There are some things that need to be adjusted.
Like refresh, adjust button functionality. Some small bugs to fix.  
It'd be great to work on this.

**Comment by r1ddl3rz** [comment]
@willok @RfidResearchGroup 
See you've updated the app. Thank you - much better. A better marking at the buttons to change the button functionality which button is left and right would be great.

**Comment by xianglin1998** [comment]
Ok, will add on next version.

**Comment by r1ddl3rz** [comment]
@xianglin1998 great work with this app.
ty

**Comment by xianglin1998** [comment]
looking forward to your further suggestions.
