### ISSUE TITLE
How to change ATS while SAK=28(JCOP41,IBM) in Chameleon Tiny？

### ISSUE THREAD

**Issue by Hodit01** [RfidResearchGroup/ChameleonMini#23]
Problem:
I cloned the M1 part of a card with chameleon tiny, but when I got the label information, I couldn't get the correct ATS.
（one plus 5T Mifare classic tool to read）
Original card info
![7UKR7DUMMWECI$8H )O40~H](https://user-images.githubusercontent.com/32798330/81138113-72f75e00-8f93-11ea-9cb4-1c3d7dc8d24b.png)
 chameleon tiny card info
![NEQ7{PVEKL)J40%5GGKO395](https://user-images.githubusercontent.com/32798330/81138118-7d195c80-8f93-11ea-8f32-3425f57fb19e.png)

Help:
1.How can I get the right ATS？
2.Where can I get relevant information if I need to modify the code and recompile it？
3.Can the author add this function like SAKMODE?
(After all, it's necessary to get the same label information)

Thank you very much if anyone could give me a hand！

**Comment by iceman1001** [comment]
1. No support for custom ATS exists.   Feel free to contribute
2. read the offical repo,  this repo's source code  and documents.
3. Custom SAK/ATQA was recent added.

closing.
