### ISSUE TITLE
Remnant of previous card when cloning new cards.

### ISSUE THREAD

**Issue by jixiangyuan** [RfidResearchGroup/ChameleonMini#35]
When using the ChameleonMini Android app, and set the button hold to ``clone'', if there was any card data in the slot previously when cloning, the Chameleon will only overwrite the data on sector 0, block 0, leave all the other data untouched, this includes keys, access conditions and value block data, which will cause errors. Please fix this. Thank you.

**Comment by iceman1001** [comment]
User failed to understand how the command works.  Closing.

**Comment by Warborn123** [comment]
I know the command `ICEMAN=PUSSYMAN`

**Comment by Warborn123** [comment]
If you turn half the time argue with me in to bug fixing, the firmware you released will be decent, but you don't becuase you are xxman.Closing a issue because of personal disputes? That's so pathetic. Wish you doing well in real life, sincerely.
