### ISSUE TITLE
Card emulation is not working anymore

### ISSUE THREAD

**Issue by Warborn123** [RfidResearchGroup/ChameleonMini#42]
Hi Iceman, the last two firmware you release completely kill the card emulation feature. Also, when you do "UID Clone", it will display "Failed" everytime. I know it is a "Pre-release" firmware, but could you at least do some simple test before you release a new firmware? Thank you very much.

**Comment by iceman1001** [comment]
Thank you for your comment.
It would help if you at least gave relevant debug information on what you did in order to verify your claim.

**Comment by Warborn123** [comment]
Thank you for your reply. 
I don't really see how could I get a debug file, and it is fairly easy to verify my claims, as you can simply upload a dump file to the chameleon mini/tiny and see if you can open a door with that. It won't work from what I saw. And you cannot even get the .bin file from the chameleon using a proxmark3, after flashing the firmware built d4a7926 and 7f310af.
As for my second claim, please open the app on your phone and click on the "UID Clone" option and see what happens. All those bugs were not found on built 152dc71. Please try it.

**Comment by iceman1001** [comment]
See my previous comment.

**Comment by Warborn123** [comment]
Well, see my previous comment, I already told you what to do. If you don't want to fix the problem, that's fine, and please don't release bs firmware like this, you are hurting the community. Go back to your proxmark3 form.

**Comment by iceman1001** [comment]
Make a proper issue with relevant debug information in order to easily replicate your issue.  Since I asked twice and you refuse to do it, I seen no possibility to help you.  You do know you can use an older release?  And why are you trying to be rude?

**Comment by Warborn123** [comment]
I'm being rude? After I told you specifically what to do, your response was "See my previous comment"? And I will say it again, I don't think I can get any debug file (tell me if you can), and the problem can be easily replicated. Did you even tried that? I have both chameleon tiny and mini, and they both stop working properly after I flashed your firmware, and when I flashed back to the previous firmware, it works again, what does that mean to you pal? And yes, I know I can always use an older release, but this section is called "Issues" for a reason. Beside, what is the point for releasing firmware that is not working? So people can tried the older release? I don't see the point. Again, I just want to say that please do some simple test before you release an new firmware. No offense.

**Comment by iceman1001** [comment]
Rude comments are never acceptable. 
1. You claim simple tests wasn't done,   they were. 
2. You claim its not working but provide no relevant debug information to verify it.
3. When asked for said information, you return rude comment and personal attacks.

**Comment by aveao** [comment]
Hi,
I was one of the people that sent the PRs.

I can partially repro this. CLONE command works, field turns on, UID gets cloned, but success isn't returned properly.

I'll bisect this and fix it after work.

I've tested on: https://github.com/RfidResearchGroup/ChameleonMini/commit/d4a79265f1fd67ba7a938438f7288efbb6f95a89

I'd appreciate it if you could tell me which commit or build is the last working one so that I don't have to manually check.

ps. Please keep in mind that CI builds are marked as pre-release, as such please expect them to have more bugs.

**Comment by Warborn123** [comment]
> Hi,
> I was one of the people that sent the PRs.
> 
> I can partially repro this. CLONE command works, field turns on, UID gets cloned, but success isn't returned properly.
> 
> I'll bisect this and fix it after work.
> 
> I've tested on: [d4a7926](https://github.com/RfidResearchGroup/ChameleonMini/commit/d4a79265f1fd67ba7a938438f7288efbb6f95a89)
> 
> I'd appreciate it if you could tell me which commit or build is the last working one so that I don't have to manually check.
> 
> ps. Please keep in mind that CI builds are marked as pre-release, as such please expect them to have more bugs.

Thank you. That's good to hear, and could you please test the case with card emulation? Clone card with only UID might work, but cloning card with multiply keys simple not working for me.

**Comment by Warborn123** [comment]
> Rude comments are never acceptable.
> 
> 1. You claim simple tests wasn't done,   they were.
> 2. You claim its not working but provide no relevant debug information to verify it.
> 3. When asked for said information, you return rude comment and personal attacks.

1. If you already did the tests, why don't you already say so? So I can check whether it's my problem or not.
2.There is now.
3.Yeah its really weird that when you treat people nice and people get rude at you for no reason huh, I guess that's how it works.

**Comment by iceman1001** [comment]
You are making the claims, the burden of proof lays upon you.  You refuse to provide relevant debug information, 

When asked for more information, you fall back to rude comments, personal attacks and you pretend that I was rude to you? Please point out where I was rude to you?

**Comment by aveao** [comment]
CLONE is only meant to clone the UID.

From README:

> Read the UID card number immediately after pressing, continue searching, and simulate immediately after reading the card

On September 18, 2020 11:12:20 AM GMT+03:00, jixiangyuan <notifications@github.com> wrote:
>> Hi,
>> I was one of the people that sent the PRs.
>> 
>> I can partially repro this. CLONE command works, field turns on, UID gets cloned, but success isn't returned properly.
>> 
>> I'll bisect this and fix it after work.
>> 
>> I've tested on: [d4a7926](https://github.com/RfidResearchGroup/ChameleonMini/commit/d4a79265f1fd67ba7a938438f7288efbb6f95a89)
>> 
>> I'd appreciate it if you could tell me which commit or build is the last working one so that I don't have to manually check.
>> 
>> ps. Please keep in mind that CI builds are marked as pre-release, as such please expect them to have more bugs.
>
>Thank you. That's good to hear, and could you please test the case with card emulation? Clone card with only UID might work, but cloning card with multiply keys simple not working for me.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/RfidResearchGroup/ChameleonMini/issues/42#issuecomment-694725462
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Warborn123** [comment]
> You are making the claims, the burden of proof lays upon you. You refuse to provide relevant debug information,
> 
> When asked for more information, you fall back to rude comments, personal attacks and you pretend that I was rude to you? Please point out where I was rude to you?

As I said several times, there is no way that I can provide debug files. PLEASE TELL ME HOW TO GET IT.
Yeah, you were never rude to me, you were like an angel all the time. There should be a medal make for you for being the niceste people in the world.

**Comment by Warborn123** [comment]
> CLONE is only meant to clone the UID. From README:
> Read the UID card number immediately after pressing, continue searching, and simulate immediately after reading the card On September 18, 2020 11:12:20 AM GMT+03:00, jixiangyuan ***@***.***> wrote: > Hi, > I was one of the people that sent the PRs. > > I can partially repro this. CLONE command works, field turns on, UID gets cloned, but success isn't returned properly. > > I'll bisect this and fix it after work. > > I've tested on: [[d4a7926](https://github.com/RfidResearchGroup/ChameleonMini/commit/d4a79265f1fd67ba7a938438f7288efbb6f95a89)]([d4a7926](https://github.com/RfidResearchGroup/ChameleonMini/commit/d4a79265f1fd67ba7a938438f7288efbb6f95a89)) > > I'd appreciate it if you could tell me which commit or build is the last working one so that I don't have to manually check. > > ps. Please keep in mind that CI builds are marked as pre-release, as such please expect them to have more bugs. Thank you. That's good to hear, and could you please test the case with card emulation? Clone card with only UID might work, but cloning card with multiply keys simple not working for me. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#42 (comment)](https://github.com/RfidResearchGroup/ChameleonMini/issues/42#issuecomment-694725462)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

My apologies, emulate dump files with multiple keys doesn't work, could you test that please?

**Comment by aveao** [comment]
> As I said several times, there is no way that I can provide debug files. PLEASE TELL ME HOW TO GET IT.

Iceman asked for debug info, which can be which commit you're running that's broken, what commit you said was working fine, what you are trying, what happens, what you expected to happen etc etc. It's a lot more painful to try and fix a bug without this information.

Also, there's no way that I know that you can get "debug files". You can however enable logging with `LOGMODE=MEMORY` (then clean memory with `LOGCLEAN`), do what you want, then download it with `LOGDOWNLOAD`. While this won't necessarily contain debug information, in my case it shows a successful read and a successful UID change, which helped me pinpoint this issue to chameleon not properly saying that CLONE was successful :)

> My apologies, emulate dump files with multiple keys doesn't work, could you test that please?

Please open a separate issue for that, and please supply debug information.

**Comment by Warborn123** [comment]
> > As I said several times, there is no way that I can provide debug files. PLEASE TELL ME HOW TO GET IT.
> 
> Iceman asked for debug info, which can be which commit you're running that's broken, what commit you said was working fine, what you are trying, what happens, what you expected to happen etc etc. It's a lot more painful to try and fix a bug without this information.
> 
> Also, there's no way that I know that you can get "debug files". You can however enable logging with `LOGMODE=MEMORY` (then clean memory with `LOGCLEAN`), do what you want, then download it with `LOGDOWNLOAD`. While this won't necessarily contain debug information, in my case it shows a successful read and a successful UID change, which helped me pinpoint this issue to chameleon not properly saying that CLONE was successful :)
> 
> > My apologies, emulate dump files with multiple keys doesn't work, could you test that please?
> 
> Please open a separate issue for that, and please supply debug information.

I understand that, but for my particular case, I don't think the debug file or log file is useful. The issue I have is that the reader of the door cannot read the card info when emulated, since there is no error in the log files, the only thing I can do is to ask you guys to do what I did in order to replicate the problem I had. And this is actually the issue, it is on the title, so I don't really think I should open a separate issue for this. Thank you.

**Comment by Akisame-AI** [comment]
and how did you do it. What did you use to flash, how did you upload the cards to the chameleon, how are you connected to the chameleon (bt or cable). Please be precise and complete in the actions you did to get this bug

**Comment by Warborn123** [comment]
> and how did you do it. What did you use to flash, how did you upload the cards to the chameleon, how are you connected to the chameleon (bt or cable). Please be precise and complete in the actions you did to get this bug

I use cable to flash the firmware, I upload the cards to the chameleon via android apps.

**Comment by Akisame-AI** [comment]
Which apps? Have you tried downloading your upload directly with the app and comparing it to your upload? There can be more reasons for it not opening a door anymore. 
You could have a hardware issues for example. Had that as well with my tiny.
Any and all strange things you observe help.

**Comment by Warborn123** [comment]
> Which apps? Have you tried downloading your upload directly with the app and comparing it to your upload? There can be more reasons for it not opening a door anymore.
> You could have a hardware issues for example. Had that as well with my tiny.
> Any and all strange things you observe help.

I used the chameleon app made by RFID group, I tried to download my upload and compare it to the original, they are exactly the same. There should not be any hardware issue, as I own both chameleons tiny and mini, and they both stop emulating when I flash the new firmware, but when I downgraded, it works. There is no anomaly from what I observed.
