### ISSUE TITLE
After flashing 7f310af7ad9218f85c1b69a74ccb26ad9b77c874 , the chameleonmini got in completely mess

### ISSUE THREAD

**Issue by qqice** [RfidResearchGroup/ChameleonMini#44]
Hi there,
A few days ago, I tried to flash the latest pre-release build 7f310af7ad9218f85c1b69a74ccb26ad9b77c874 into my ChameleonMini.
Since then, everyting went into a completely mess:
1.long press to trigger "Clone" was not available;
2.All dumps I uploaded to the ChameleonMini got wrong.
For example, the dump file I uploaded is: 
[before.zip](https://github.com/RfidResearchGroup/ChameleonMini/files/5261657/before.zip)
and after the upload process, I IMMEDIATELY downloaded the same dump, but it turns into: 
[after.zip](https://github.com/RfidResearchGroup/ChameleonMini/files/5261671/after.zip)
I also tried to change the UID, but it doesn't wrok.

**To make things worse, no matter how I tried to flash back to any previous firmware, the problem 2 exists anyway.**

Please help. Thanks.

**Comment by Akisame-AI** [comment]
Hey there,

Could you upload your before and after in a different format as I can't read the bin files without a lot of effort.
You may also want to have a look at this issue https://github.com/RfidResearchGroup/ChameleonMini/issues/29

Regards

**Comment by qqice** [comment]
BEFORE
0 扇区
0 区块: 26 C3 A7 54 16 08 04 00 01 6A 41 B2 79 D1 15 1D
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: B1 B2 B3 B4 B5 B6 FF 07 80 69 68 C3 A0 59 E4 3B

1 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: C1 C2 C3 C4 C5 C6 FF 07 80 69 5F 81 A6 7E 20 B9

2 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: D1 D2 D3 D4 D5 D6 FF 07 80 69 28 C5 39 A1 32 F8

3 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: E1 E2 E3 E4 E5 E6 FF 07 80 69 94 7C 28 6E 73 5A

4 扇区
0 区块: 01 00 01 E4 82 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 72 6F 37 11 75 5D FF 07 80 69 47 6F 09 2E 7A 6B

5 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 11 75 5D 72 6F 37 FF 07 80 69 67 A2 96 B7 38 E5

6 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: A1 A2 A3 A4 A5 A6 FF 07 80 69 A9 38 C5 91 E5 4A

7 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 72 FF 75 6F 37 11 FF 07 80 69 65 87 DD 30 A9 5C

8 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 75 6F 37 11 75 5D FF 07 80 69 67 3C 95 7A 32 9E

9 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 1A 2B 3C 4D 5E 6F FF 07 80 69 5D 83 F0 56 E7 2C

10 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 1F 2E 3D 4C 5B 6A FF 07 80 69 67 3A 04 E5 73 C2

11 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 1A 3C 5B 7D 9E 0F FF 07 80 69 7B 78 3E 95 7A 2C

12 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 82 9C 5E BA 84 D2 FF 07 80 69 78 3C 90 58 F2 A3

13 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: CD 23 8F 2D B1 0C FF 07 80 69 92 B6 34 A1 3E 26

14 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: 20 2D 10 2D 70 D4 FF 07 80 69 D2 7E 30 9A 18 4C

15 扇区
0 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
1 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
2 区块: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
3 区块: BF 75 DE 83 CA 01 FF 07 80 69 EF 18 AF 15 DF 16

**Comment by qqice** [comment]
AFTER
0 扇区
0 区块: 7E C3 FF 74 76 58 BC 38 79 6A 71 BA 79 D1 3D 3D
1 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 D8 28 38
2 区块: 78 40 78 38 70 50 18 38 78 40 78 38 60 58 38 38
3 区块: F9 F2 FB BC B5 FE FF 3F F8 69 78 FB F0 59 FC 3B

1 扇区
0 区块: 7A 40 78 30 70 78 38 38 79 40 78 30 70 78 38 38
1 区块: 78 40 78 38 70 78 38 38 78 40 58 38 70 78 38 38
2 区块: 78 50 78 28 70 48 38 38 78 40 78 38 70 58 38 28
3 区块: F8 C2 FB FC E5 DE FF 3F F8 69 3F B9 E6 7E 38 B9

2 扇区
0 区块: 79 40 78 30 70 78 38 38 78 C0 78 38 70 78 38 38
1 区块: 78 40 78 38 70 78 38 38 78 40 78 38 60 58 38 38
2 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 78 38 38
3 区块: F9 D3 FB FC D5 9E FF 3F F8 69 7A FD 79 F9 3A F8

3 扇区
0 区块: 78 40 78 38 70 78 38 38 78 40 78 38 60 58 38 38
1 区块: 58 40 78 78 60 58 38 38 78 40 78 38 60 58 38 38
2 区块: 78 60 78 28 70 58 38 28 78 40 78 38 70 50 18 38
3 区块: F9 E0 FB FC E5 F6 FF 3F F8 69 FC 7C 78 7E 7B 3A

4 扇区
0 区块: 59 40 79 EC F2 50 18 38 78 40 78 38 60 58 38 38
1 区块: 7A 40 78 30 70 78 38 38 79 40 78 30 70 58 38 28
2 区块: 78 40 78 38 60 58 38 38 78 40 78 38 60 58 28 38
3 区块: 7A 6F 7F 39 75 5D FF 3D D8 69 7F 7F 79 7E 7A 79

5 扇区
0 区块: 78 40 78 38 70 78 38 38 78 40 78 38 60 58 38 38
1 区块: 78 40 78 38 60 58 38 38 78 40 78 38 70 78 38 38
2 区块: 78 40 78 38 70 50 18 38 78 40 78 38 70 78 38 38
3 区块: 79 7D 7D 7A 7F 37 FF 2F F8 69 7F B2 76 FF 38 FD

6 扇区
0 区块: 78 40 78 38 70 D8 28 38 78 40 78 38 70 78 38 38
1 区块: 78 60 78 28 70 78 38 38 78 40 78 38 60 58 28 38
2 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 58 38 28
3 区块: F9 E2 FB BC F5 BE FF 3F F8 69 E9 38 F5 D9 FD 7A

7 扇区
0 区块: 78 40 78 38 74 58 28 30 78 00 68 38 70 78 38 38
1 区块: 78 40 78 38 60 58 38 38 78 40 78 38 70 58 18 38
2 区块: 78 40 78 38 70 78 38 38 58 40 78 78 70 78 38 38
3 区块: 7B FF 7D 7F 77 59 FF 3F F8 69 7D BF FD 50 B9 7C

8 扇区
0 区块: 58 40 78 78 70 78 38 38 78 40 78 38 20 58 28 38
1 区块: 78 44 58 38 70 D8 28 38 38 40 78 38 70 58 18 28
2 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 78 38 38
3 区块: 7D 6F 7E 39 75 5D FF 3D F8 6D 7F 3C F5 7A 3A BE

9 扇区
0 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 78 38 38
1 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 58 38 28
2 区块: 58 40 78 3C 60 58 38 38 78 40 78 38 70 78 38 38
3 区块: 7A 6B 7C FD 7E 5F FF 37 F8 69 7D BB F0 5E FF 3C

10 扇区
0 区块: 78 40 78 38 70 78 38 38 78 40 58 38 60 58 38 38
1 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 78 38 38
2 区块: 78 00 78 38 68 58 18 38 78 40 78 38 70 78 38 38
3 区块: 7F 6E 7D 6C 7B 7A FF 3F F8 69 7F 3A 64 FD 73 FA

11 扇区
0 区块: 58 40 78 78 60 58 38 38 78 44 58 38 72 58 38 38
1 区块: 78 40 78 38 70 58 38 28 78 50 78 28 70 D8 28 38
2 区块: 58 40 78 78 70 78 38 38 78 40 78 38 70 50 18 38
3 区块: 7A 7C 7B 7D FE 5F FF 3D F8 61 7B 78 7E DD 7A 3C

12 扇区
0 区块: 78 40 78 38 70 50 18 38 78 40 78 38 70 78 38 38
1 区块: 78 40 78 38 70 50 18 38 78 40 78 38 70 58 38 28
2 区块: 78 40 78 38 70 78 38 38 78 40 78 38 68 58 18 38
3 区块: FA DC 7E BA F4 D8 FF 3F F8 69 78 3C F0 58 FA BB

13 扇区
0 区块: 79 40 78 30 70 78 38 38 78 40 78 38 70 78 38 38
1 区块: 78 40 78 38 74 58 28 30 78 40 78 38 70 48 38 38
2 区块: 7A 40 78 30 60 58 38 38 78 40 78 38 71 58 38 20
3 区块: FD 63 FF 3D F1 5C FF 2F B8 69 FA BE 7C F9 3E 3E

14 扇区
0 区块: 58 40 78 78 70 78 38 38 78 40 78 38 60 58 38 38
1 区块: 78 40 78 38 50 58 38 38 78 40 78 38 70 78 38 38
2 区块: 78 40 78 38 70 78 38 38 70 40 70 38 70 78 38 38
3 区块: 78 7D 78 3D 70 DC FF 2F FC 69 FA 7E 70 DA 38 7C

15 扇区
0 区块: 78 40 78 38 70 D8 28 38 78 40 78 38 70 78 38 38
1 区块: 78 40 78 38 70 78 38 38 78 60 78 28 70 78 38 38
2 区块: 78 40 78 38 70 78 38 38 78 40 78 38 70 78 38 38
3 区块: FF 75 FE BB FA 51 FF 3F F8 69 FF 38 DF 5D FF 3E

**Comment by Akisame-AI** [comment]
This looks like your mram bits are flipped. Could you upload and download a sequential dump like
000000000
111111111
222222222
333333333
444444444
That way we can see which bits are stuck and confirm the problem.
If your ram does have its bits flipped (by for example a magnet) it is unfixable
