### ISSUE TITLE
TinyPro(BLE) DFU unsupported!

### ISSUE THREAD

**Issue by Knocks83** [RfidResearchGroup/ChameleonMini#61]
Hello, I'm trying to upgrade the BLE firmware of my Chameleon Tiny Pro, but when I try tapping on the "BLE CMD Version" field I get the error message "TinyPro(BLE) DFU unsupported!".
How can I upgrade my BLE firmware (if there is a newer version)?

My infos:
| Field | Value |
| ------------- | ------------- |
| BLE CMD Version  | 1.0 Fixed |
| BLE Firmware Version | 2020-03-29 V2.1 |
| AVR Firmware Version | ChameleonMini RevG compiled at 210202 13:31:11(33a8750) using LUFA 151115 with AVR-GCC 5.4.0. |
| CMD Kernel Version | 1.158 |
| Max Slot Limit | 8 |
| Max button Limit | 2 |
| Firmware Support | Rev.G RDV2.0(mini & Tiny & TinyPro) |
| App Version Name | 2020-10-29_1155 |
| App Version Code | 107 |

**Comment by nieldk** [comment]
You cant. 

Chameleon tiny pro BLE, it is DA14531, and is OTP(one time program) chip. So , we can not update it.

**Comment by mariovirgili** [comment]
So it's not upgradable at all? Even with usb connection?

**Comment by nieldk** [comment]
> So it's not upgradable at all? Even with usb connection?

you cant update the BLE firmware. But of course you can update the Chameleon.

**Comment by mariovirgili** [comment]
And updating the chameleon fw will not remove BLE capabilities? Sorry for the noob question, but I fear of removing BLE connection... I just need to be sure to avoid damage

**Comment by nieldk** [comment]
> And updating the chameleon fw will not remove BLE capabilities? Sorry for the noob question, but I fear of removing BLE connection... I just need to be sure to avoid damage

No, the Chameleon Tiny Pro firmware, and the BLE firmware, are two different firmware, residing on two different chips.

**Comment by raaffq** [comment]
> > And updating the chameleon fw will not remove BLE capabilities? Sorry for the noob question, but I fear of removing BLE connection... I just need to be sure to avoid damage
> 
> No, the Chameleon Tiny Pro firmware, and the BLE firmware, are two different firmware, residing on two different chips.

Hello , how to update TinyPro FW using android app? Any idea?

**Comment by mariovirgili** [comment]
It’s not possible. You need windows or, better, linux environment to update firmware.
I suggest you the following video: https://youtu.be/dOIbKCPY-mE with step by step instructions using linux

**Comment by raaffq** [comment]
> It’s not possible. You need windows or, better, linux environment to update firmware.
> I suggest you the following video: https://youtu.be/dOIbKCPY-mE with step by step instructions using linux

wow i didn't know that , same guy showing how to update via app but not working in my case https://www.youtube.com/watch?v=OrAw1wqS7Ts ,I will yous mac for update byt need to find good tutorial for that. thanks
