### ISSUE TITLE
Cloning does not work

### ISSUE THREAD

**Issue by D-Jy-lab** [RfidResearchGroup/ChameleonMini#7]
克隆功能没有反应，
Tiny用手机APP操作读卡时会断开连接

**Comment by xianglin1998** [comment]
断开连接是指读卡时和卡片断开连接还是读卡时和整个变色龙断开连接?

类似的问题如何复现，请尽可能的提供完整的步骤，谢谢你的支持。

**Comment by D-Jy0329** [comment]
用数据线连接时，使用app的读卡功能会导致变色龙卡死。
另外将变色龙按钮设置为克隆时，操作并没有反应。

**Comment by temal-** [comment]
I run into the same issue.

When I compile a firmware from the master branch of the upstream emsec repo, I can directly issue a `CLONE` command and everything seems to work.

Commit: https://github.com/emsec/ChameleonMini/commit/b58ab584716cc3183eed4f8f078027d064ba3a30

Example:

```
VERSION?
101:OK WITH TEXT
ChameleonMini RevG 200209 using LUFA 151115 compiled with AVR-GCC 5.4.0. Based on the open-source NFC tool ChameleonMini. https://github.com/emsec/ChameleonMini commit b58ab58
SETTING?
101:OK WITH TEXT
1
CONFIG?
101:OK WITH TEXT
NONE
TIMEOUT?
101:OK WITH TEXT
5000 ms
UID?
101:OK WITH TEXT
NO UID.
CLONE
101:OK WITH TEXT
Cloned OK!
UID?
101:OK WITH TEXT
FOOBAR12
```

When I compile a firmware from the proxgrind branch of the RfidResearchGroup repo, I guess I have to first set the CONFIG to NONE, because it is different in this repo? At the end it doesn't matter if I do so or not, because I cannot clone the same card that works on the original firmware.

The same happens on the latest firmware in the `Firmware/Chameleon-Mini/Latest` directory.

Commit: https://github.com/RfidResearchGroup/ChameleonMini/commit/de4274d934fb79d15eec8877967393480229c29b

Example:

```
VERSION?
101:OK WITH TEXT
ChameleonMini RevG compiled at 200209 14:23:31(de4274d) using LUFA 151115 with AVR-GCC 5.4.0.
UID?
101:OK WITH TEXT
FFFFFFFF
SETTING?
101:OK WITH TEXT
1
CONFIG?
101:OK WITH TEXT
MF_CLASSIC_1K
CONFIG=NONE
100:OK
CLONE
```

The `TIMEOUT` does never trigger and the therefore I have to restart the Chameleon Mini.

**Comment by xianglin1998** [comment]
我目前测试了APP包括手动和按钮自动操作克隆的功能。

0. 硬件与固件与APP
硬件：Chameleon Tiny
固件：RRG(51CE8FB) 2019-12-24
软件：从谷歌市场下载的最新版本的客户端

1. 参数配置： 
超时： 5000ms
卡槽模式： MF_CLASSIC_1K
按钮单击：CLONE

2. 步骤
安卓打开手机APP，链接Tiny
将Tiny放在卡片上面，执行CLONE命令，返回Cloned OK!
将Tiny从卡片上面移开，执行CLONE命令，返回TIMEOUT
将Tiny按钮功能设置为CLONE，移除设备链接，然后将Tiny放在卡片上面，单击按钮，CLONE成功
将Tiny按钮功能设置为CLONE，移除设备链接，不放置到卡片上面，单击按钮，超时
将Tiny按钮功能设置为CLONE，不移除设备链接，放置到卡片上面，单击按钮，CLONE成功
将Tiny按钮功能设置为CLONE，不移除设备链接，不放置到卡片上面，单击按钮，超时且数据混乱(APP)

***************************************************************************************

At present, I have tested the function of APP including manual and button automatic operation clone.



0. Hardware and firmware and app

Hardware: Chameleon tiny

Firmware: RRG (51ce8fb) 2019-12-24

Software: the latest version of the client downloaded from Google Market



1. Parameter configuration:

Timeout: 5000ms

Card slot mode: MF? Class? 1K

Button click: Clone



2. steps

Android opens mobile app and links to tiny

Put tiny on the card, execute the clone command, and return to closed ok!

Remove tiny from the card, execute the clone command, and return to timeout

Set the tiny button function to clone, remove the device link, and then place tiny on the card. Click the button, and clone succeeds

Set the tiny button function to clone, remove the device link, do not place it on the card, click the button, timeout

Set the tiny button function to clone, do not remove the device link, and place it on the card. Click the button, and clone succeeds

Set the tiny button function to clone, do not remove the device link, do not place it on the card, click the button, timeout and data confusion (APP)

**Comment by temal-** [comment]
Thanks for the translation! :)

It works with 51ce8fb for me too.

But the files in https://github.com/RfidResearchGroup/ChameleonMini/tree/proxgrind/Firmware/Chameleon-Mini/Latest are compiled of commit 11a8cc5, which does not work for me on the Tiny or Mini.
When I use the `CLONE` command on 11a8cc5, LED1+LED2 start flashing and nothing happens until I restart the Tiny, Mini.

When I compile from `de4274d`, then the LEDs don't flash but still nothing happens after `CLONE`.

**Comment by D-Jy0329** [comment]
固件:11a8cc5(1月8号的固件)
[AVR固件20200108-11a8cc5.zip](https://github.com/RfidResearchGroup/ChameleonMini/files/4179940/AVR.20200108-11a8cc5.zip)
这个固件测试没有发现问题，但是因为返回RATS，某些带有防火墙的读卡器不能识别，无法使用。
固件:b867f3c和2246c90
[AVR固件20200130-2246c90.zip](https://github.com/RfidResearchGroup/ChameleonMini/files/4179938/AVR.20200130-2246c90.zip)
[AVR固件20200205-b867f3c.zip](https://github.com/RfidResearchGroup/ChameleonMini/files/4179939/AVR.20200205-b867f3c.zip)
解决了兼容问题，但是Clone无法使用，MINI蓝牙连接APP没有问题。Tiny使用数据线连接使用GetUID(读取卡号)时变色龙1，2灯会交替闪烁，并且卡死，重新连接其他功能没问题，但使用GetUID会再次卡死。
APP版本：2020-01-28_1051
https://play.google.com/store/apps/details?id=com.proxgrind.chameleon
这个问题可以被修复吗？

**Comment by xianglin1998** [comment]
@D-Jy0329 我这边会帮您向固件的开发者提交这个问题，有结果我会反馈给您，谢谢您的反馈哈：）

**Comment by D-Jy-lab** [comment]
已解决
[Uploading AVR固件.zip…]()
