### ISSUE TITLE
fails to pair with android app

### ISSUE THREAD

**Issue by JamesRHarris** [RfidResearchGroup/ChameleonMini#8]
I have updated to the latest firmware published 

ChameleonMini RevG 191226 using LUFA 151115 compiled with AVR-GCC 4.9.2. Based on the open-source NFC tool ChameleonMini. https://github.com/emsec/ChameleonMini commit d6d183b

This is listed at LATEST at 
https://github.com/RfidResearchGroup/ChameleonMini/tree/proxgrind/Firmware/Chameleon-Mini/Latest

On android QQ1B.200105.004  running on a pixel 4XL the Chameleon app is unable to connect over bluetooth.  The BLE-Chameleon shows up in the devices found but pairing fails.

**Comment by D-Jy0329** [comment]
你应该刷编译后的固件
[Chameleon-Mini.zip](https://github.com/RfidResearchGroup/ChameleonMini/files/4143720/Chameleon-Mini.zip)

**Comment by JamesRHarris** [comment]
If a newer build is required for BLE support can we get  that updated at https://github.com/RfidResearchGroup/ChameleonMini/tree/proxgrind/Firmware/Chameleon-Mini/Latest or  tag a 'release' ?

**Comment by willok** [comment]
I forgot to update the file in /Firmware/Chameleon-Mini/Latest, now updated.
I'm sorry.
