### ISSUE TITLE
How to re-init slot data after clone?

### ISSUE THREAD

**Issue by xeonxu** [RfidResearchGroup/ChameleonMini#87]
I would like to reset slot data as default after cloning a UID. How can I get that?

**Comment by alphakdelta** [comment]
Are you on an Android app or the iOS Beta test. You should be able to reset to a MiFare Classic 1k, set the UID to “12345678” and clear any data. But that is the long way. On the android, iOS and desktop there is an option to reset or clear the slot. Smash that button and it will reset that slot.
